services:
  helmsman:
    image: helmsman:dev
    build: .
    container_name: helmsman
    network_mode: host
    ipc: host
    environment:
      - DISPLAY=${DISPLAY}
      - QT_X11_NO_MITSHM=1
      - __NV_PRIME_RENDER_OFFLOAD=1
      - __GLX_VENDOR_LIBRARY_NAME=nvidia
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix:rw
      - ../ws:/ws
    group_add:
      - "44"     # video  (host GID)
      - "992"    # render (host GID)
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu, graphics, display]
    stdin_open: true
    tty: true